name: notion-pipeline (UTC+8: 14:30 / 19:30 / 23:59)

on:
  schedule:
    - cron: "30 6 * * *"   # 14:30 UTC+8
    - cron: "30 11 * * *"  # 19:30 UTC+8
    - cron: "59 15 * * *"  # 23:59 UTC+8
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_SOURCES_DB: ${{ secrets.NOTION_SOURCES_DB }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      NOTION_RULES_DB: ${{ secrets.NOTION_RULES_DB }}
      NOTION_DAILY_PARENT: ${{ secrets.NOTION_DAILY_PARENT }}
      TZ: ${{ vars.TZ || 'Asia/Shanghai' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        run: python -m src.pipeline
